sed $1  -i -e 's/sscan/fprint/g'
sed $1  -i -e 's/&/Table->/g'
sed $1  -i -e 's/argv\[argcount+1\],/,/g'
sed $1  -i -e 's/fprintf(/fprintf(fp/g'
sed $1  -i -e 's/%lf/%g/g'
sed $1  -i -e 's/%d/-  %d  /g'
sed $1  -i -e 's/%g/-  %g  /g'
sed $1  -i -e 's/%s/-  %s  /g'
sed $1  -i -e 's/%f/-  %f  /g'
